### ISSUE TITLE
Implement extra process handling in CLI to allow stop of running sessions.

### ISSUE THREAD

**Issue by insightmind** [insightmind/MORR#77]
As we want the Recording to be cancelled correctly by the CLI we need to create a separate subprocess which runs the actual MORR core. We then can allow the CLI to still be responsive and accept user interactions such as a stop or cancel command, as the message loop will then no longer block the CLI.

**Comment by Gordin508** [comment]
Note: In theory, we could completely replace the message loop with the GlobalHook, which already runs in a separate thread. I don't know if the modules will still require some functionality from the MessageLoop however, so that has to be checked before.

**Comment by insightmind** [comment]
I think the problem we had was that the hooks were not efficient enough without a message loop. However I can check if we still need the message queue.

**Comment by sjend** [comment]
The problem we had was that low-level hooks don't actually work unless there is a windows message pump attached to the current process - this is not the case for a standard console application, so we had to roll our own. I don't think the current GlobalHook implementation provides or ensures a message pump - I couldn't get the keyboard module working without one (even on the latest branch with the CLI in a different process)

**Comment by Gordin508** [comment]
Since the current implementation gets it's WM_KEYDOWN events from the low-level hook, the GlobalHook will indeed not replace it (as you correctly observed, it doesn't pump the messages), and as already stated by @sjend in #74, the global hook will probably never be stable enough to completely replace the LL hook (which is a fair point). My idea was based on the premise that the LL hook won't see usage anymore, but as that isn't the case, i suggest going ahead with the original idea of moving the message pump to a separate thread.
