### ISSUE TITLE
Cancelling monitor selection results in undefined behavior

### ISSUE THREAD

**Issue by Gordin508** [insightmind/MORR#99]
Current behavior: When starting a session and clicking the "cancel" button in the GraphicsCapturePicker, the recording session is still started without error and the other encoder(s) seem to be working. When closing the session (only tested in CLI), the message `Closing MORR. This may take some time!` appears, yet the program never closes by itself (the message `Recording session stopped` is expected to appear afterwards, which does not happen). A video file is not created.

Tested on branch feature/97-multi-transcoder-support on a windows version where using the picker is mandatory.

Relevant file: **MORR/Data/Capture/Video/Desktop/DesktopCapture.cs**, lines 36ff.

Expected behavior: Either the recording process does not start at all, or it should at least terminate correctly when choosing to end the session.

**Comment by sjend** [comment]
As there is no proper way for a module to stop capturing, I have choosen to just simply thrown an exception. The selection mechanism runs at an undetermined point during capture start, we therefore unfortunately will be unable to simply stop all consumers by notifying them that no events will be enqueued as capture item acquisition failed, as they may not yet have started consuming. As such, there is no other direct way to gracefully ignore failure in this module or stop capture otherwise, which I think is fine, as the picker is mostly intended as a backup to support Build 1809, not as the primary selection mechanism (you could also pick a single window with it, which we cannot verify, so I think having this mechanism be reasonably restricted should be acceptable).

**Comment by sjend** [comment]
Closed with #100
